import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../core/utils/date_formatter.dart';
import '../../models/organization_model.dart';

class OrganizationCard extends StatelessWidget {
  final OrganizationModel organization;
    final VoidCallback onTap;

      const OrganizationCard({super.key, required this.organization, required this.onTap});

        @override
          Widget build(BuildContext context) {
              return InkWell(
                    onTap: onTap,
                          borderRadius: BorderRadius.circular(20),
                                child: Container(
                                        padding: const EdgeInsets.all(14),
                                                decoration: BoxDecoration(
                                                          color: Colors.white,
                                                                    borderRadius: BorderRadius.circular(20),
                                                                              border: Border.all(color: AppTheme.divider),
                                                                                        boxShadow: AppTheme.cardShadow,
                                                                                                ),
                                                                                                        child: Row(
                                                                                                                  children: [
                                                                                                                              ClipRRect(
                                                                                                                                            borderRadius: BorderRadius.circular(14),
                                                                                                                                                          child: SizedBox(
                                                                                                                                                                          width: 56,
                                                                                                                                                                                          height: 56,
                                                                                                                                                                                                          child: organization.logoUrl != null
                                                                                                                                                                                                                              ? CachedNetworkImage(
                                                                                                                                                                                                                                                      imageUrl: organization.logoUrl!,
                                                                                                                                                                                                                                                                              fit: BoxFit.cover,
                                                                                                                                                                                                                                                                                                      placeholder: (_, __) => Container(color: AppTheme.surfaceGrey),
                                                                                                                                                                                                                                                                                                                              errorWidget: (_, __, ___) => Container(
                                                                                                                                                                                                                                                                                                                                                        color: AppTheme.primaryBlueLight,
                                                                                                                                                                                                                                                                                                                                                                                  child: const Icon(Icons.apartment_rounded, color: AppTheme.primaryBlue),
                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                    : Container(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            color: AppTheme.primaryBlueLight,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: const Icon(Icons.apartment_rounded, color: AppTheme.primaryBlue),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(width: 12),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Expanded(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: Column(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          crossAxisAlignment: CrossAxisAlignment.start,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                organization.name,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxLines: 1,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        overflow: TextOverflow.ellipsis,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style: Theme.of(context).textTheme.titleMedium,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(height: 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      organization.category,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: const TextStyle(fontSize: 13, color: AppTheme.primaryBlue, fontWeight: FontWeight.w600),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Row(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const Icon(Icons.call_outlined, size: 14, color: AppTheme.textSecondary),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const SizedBox(width: 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              PhoneFormatter.format(organization.phone),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: Theme.of(context).textTheme.bodyMedium,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const Icon(Icons.chevron_right_rounded, color: AppTheme.textSecondary),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
